In [1]:
# tensor multiplication

import tensorflow.keras as keras
import numpy as np
from numpy.random import randint, seed
from numpy import tensordot
from pprint import pprint

In [2]:
np.__version__

'1.26.4'

In [3]:
seed(1000)

r1 = randint(0,9, size=(3,4,4))
r2 = randint(-3,3, (4,3))
print(r1.shape, r2.shape)
pprint(r1);print();pprint(r2)

(3, 4, 4) (4, 3)
array([[[3, 7, 7, 0],
        [1, 0, 8, 4],
        [4, 4, 2, 8],
        [2, 4, 2, 5]],

       [[5, 4, 0, 4],
        [2, 5, 4, 7],
        [0, 4, 7, 1],
        [0, 2, 1, 7]],

       [[1, 5, 6, 5],
        [7, 8, 8, 2],
        [2, 6, 3, 3],
        [6, 5, 8, 4]]])

array([[-2, -3, -2],
       [-2, -3, -3],
       [-3, -1,  0],
       [-2,  2,  0]])


In [4]:
prod = tensordot(r1, r2, (2,0))
print(r1.shape, r2.shape, prod.shape)
pprint(prod)

(3, 4, 4) (4, 3) (3, 4, 3)
array([[[-41, -37, -27],
        [-34,  -3,  -2],
        [-38, -10, -20],
        [-28, -10, -16]],

       [[-26, -19, -22],
        [-40, -11, -19],
        [-31, -17, -12],
        [-21,   7,  -6]],

       [[-40, -14, -17],
        [-58, -49, -38],
        [-31, -21, -22],
        [-54, -33, -27]]])


In [5]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Multiply
import numpy as np

print(Multiply()([np.array([1,2,3,4,4,4]).reshape(2,3), np.array([1,0])]))

tf.Tensor(
[[1 2 3]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [6]:
input_1 = Input(shape=(None, 3))
mask_1 = Input(shape=(None, 1))

net = Multiply()([input_1, mask_1])
net1 = Model(inputs=[input_1, mask_1], outputs=net)

print(np.array([1,2,3,4,4,4]).reshape(1,2,3))
print()
print(np.array([1,0]).reshape(1,2))
print()
out1 = net1.predict([np.array([1,2,3,4,4,4]).reshape(1,2,3), np.array([1,0]).reshape(1,2)])
print(out1); print(type(out1))

[[[1 2 3]
  [4 4 4]]]

[[1 0]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[[[1. 2. 3.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


In [7]:
out1 * 4 + 1

array([[[ 5.,  9., 13.],
        [ 1.,  1.,  1.]]], dtype=float32)